import Head from "next/head";
import useSWR from "swr";
import styles from "@/styles/Mobile.module.css";

export const Mobile = () => {
  const fetcher = (url) => fetch(url).then((r) => r.json());
  const { data } = useSWR("/api/tracks", fetcher);
  return (
    <>
      <Head>
        <title>Daril Insan Kamil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.profilepic}>
          <img src="./minaa.png" alt="minaa" className={styles.pic} />
        </div>
        <div className={styles.name}>
          <p>Daril Insan Kamil</p>
        </div>
        <div className={styles.job}>
          <p>Gak Tau Jadi apa</p>
        </div>
        <div className={styles.music}>
          <img
            src={data?.albumImageUrl}
            alt={data?.title}
            width={60}
            height={60}
            className={styles.albumimg}
          />
          <div className={styles.credit}>
            <p className={styles.curr}>CURRENT PLAYING</p>
            <p className={styles.titlesong}>{data?.title}</p>
            <p className={styles.artist}>{data?.artist}</p>
          </div>
        </div>
        <div className={styles.quote}>
          <img src="./ewniah.svg" alt="ewniah" />
        </div>
        <div className={styles.project}>
          <p>Project</p>
          <img src="./arrow.svg" alt="arrow" className={styles.arrow} />
        </div>
      </main>
    </>
  );
};
